version: "3.8"
services:
  # TradeSage Backend Service
  backend:
    build: ./backend
    container_name: tradesage-backend
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  # TradeSage Frontend Service
  frontend:
    build: ./frontend
    container_name: tradesage-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # Redis Service for Caching
  redis:
    image: redis:alpine
    container_name: tradesage-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
