version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
